[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "https://xenostar-2020.netlify.app/*"
  to = "https://www.xenostar.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/bryan-leewood/"
