[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/bryan-leewood-86858415/"

[[redirects]]
  from = "https://xenostar-2020.netlify.app/"
  to = "https://www.xenostar.net/"
  status = 301